# Generated by Django 3.2 on 2021-05-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_no', models.IntegerField(primary_key=True, serialize=False, verbose_name='書籍番号')),
                ('name', models.CharField(max_length=255, verbose_name='書籍名')),
                ('publisher', models.CharField(blank=True, max_length=255, verbose_name='出版社')),
                ('category', models.CharField(blank=True, max_length=255, verbose_name='カテゴリ')),
            ],
        ),
    ]
